- name: Set max virtual memory areas to production value
  command: sysctl -w vm.max_map_count=262144

- name: Enable disable-transparent-huge-pages service
  service:
    name: disable-transparent-huge-pages
    state: started
    enabled: yes
