- name: Install docker python package
  ansible.builtin.pip:
    name: docker

- name: Run portainer agent docker container
  docker_container:
    name: portainer_agent
    published_ports:
      - 9001:9001
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    image: portainer/agent:latest





# docker run -d -p 9001:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:latest
