- hosts: mongodb
  become: true
  pre_tasks:
    - name: Update apt cache if required
      apt: update_cache=yes cache_valid_time=86400
    - name: Install rsync on Debian_11
      apt:
        name: rsync
  roles:
    - community.mongodb.mongodb_linux
    - community.mongodb.mongodb_repository
    - { role: community.mongodb.mongodb_install }
    - { role: community.mongodb.mongodb_mongod, authorization: false, mongod_port: 16969, bind_ip: "localhost, {{ private_ip }}, {{ inventory_hostname }}", skip_restart: false }

  tasks:
    - name: Upload custom mongosh scripts to set up users and replica sets
      ansible.posix.synchronize:
        src: "{{playbook_dir}}/../services/mongodb"
        dest: "/home/dark0ne"
        use_ssh_args: true
      run_once: true
    - name: Run custom mongosh script
      command: mongosh localhost:16969 /home/dark0ne/mongodb/setup_mongodb.js
      environment:
        MONGODB_ADMIN_PWD: "{{ mongodb_admin_pwd }}"
      run_once: true

- hosts: mongodb
  roles:
    - { role: community.mongodb.mongodb_mongod, mongod_port: 16969, bind_ip: "localhost, {{ private_ip }}, {{ inventory_hostname }}", skip_restart: false }

