# Set up config servers replicaset
- hosts: mongodb-cfgsrv
  become: true
  pre_tasks:
    - name: Update apt cache if required
      apt: update_cache=yes cache_valid_time=86400
    - name: Install rsync on Debian_11
      apt:
        name: rsync
  roles:
    - community.mongodb.mongodb_linux
    - community.mongodb.mongodb_repository
    - mongodb-preinstall
    - community.mongodb.mongodb_install
    - { role: community.mongodb.mongodb_config, authorization: false, config_port: 18585, bind_ip: "localhost, {{ private_ip }}, {{ inventory_hostname }}", skip_restart: false }

  tasks:
    - name: Upload custom mongosh scripts to set up users and replica sets
      ansible.posix.synchronize:
        src: "{{playbook_dir}}/../services/mongodb"
        dest: "/home/dark0ne"
        use_ssh_args: true
      run_once: true

    - name: Run script to set up replicaset
      command: mongosh localhost:18585 /home/dark0ne/mongodb/setup_cfg_replicaset.js
      run_once: true

    - name: Wait for replicaset to come online
      ansible.builtin.wait_for:
        timeout: 10
      delegate_to: localhost
      become: false

    - name: Run script to set up users
      command: mongosh localhost:18585 /home/dark0ne/mongodb/setup_cfg_users.js
      environment:
        MONGODB_ADMIN_PWD: "{{ mongodb_admin_pwd }}"
      run_once: true


- hosts: mongodb-cfgsrv
  become: true
  roles:
    - { role: community.mongodb.mongodb_config, config_port: 18585, bind_ip: "localhost, {{ private_ip }}, {{ inventory_hostname }}", skip_restart: false }

