- hosts: all
  become: true
  roles:
    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: monitoring

    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: logging

    - role: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
