- hosts: redis
  become: true
  pre_tasks:
    - name: Update apt cache if required
      apt: update_cache=yes cache_valid_time=86400
    - name: Install rsync on Debian_11
      apt:
        name: rsync
  roles:
    - redis

  # tasks:
  #   - name: Upload custom mongosh scripts to set up users and replica sets
  #     ansible.posix.synchronize:
  #       src: "{{playbook_dir}}/../services/mongodb"
  #       dest: "/home/dark0ne"
  #       use_ssh_args: true
  #     run_once: true
  #
  #   - name: Run script to set up replicaset
  #     command: mongosh localhost:16969 /home/dark0ne/mongodb/setup_replicaset.js
  #     run_once: true- name: Sleep for 300 seconds and continue with play
